# Generated by Django 2.2.5 on 2019-09-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
